# Generated by Django 3.1 on 2020-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_details_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='bloodgrp',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, null=True),
        ),
    ]
